title: Lu Wang | Shenzhen University
baseURL: 'https://luwang-szu.github.io/'
defaultContentLanguage: en
languageCode: en-us
hasCJKLanguage: true
enableRobotsTXT: true
enableGitInfo: false
disableKinds: [taxonomy, term]
disableAliases: false
outputs:
  home: [HTML, RSS]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 85
  anchor: smart
markup:
  goldmark:
    renderer:
      unsafe: false
timeout: 120s
