en:
  languageCode: en-US
  languageName: English
  weight: 1
zh:
  languageCode: zh-CN
  languageName: 简体中文
  weight: 2
  title: 王璐 | 深圳大学
  params:
    description: 王璐，深圳大学计算机与软件学院教授。研究方向包括无线网络、物联网、智能感知、移动与可穿戴计算及人机交互。
